name: Terraform deployment
on:
  [push, workflow_dispatch]
jobs:
  
  terraform:
     name: "Terraform working directory"
     runs-on: ubuntu-latest
     permissions:
        id-token: write
        contents: read
     env:
        AWS_REGION: 'eu-west-1'
     defaults:
        run:
         shell: bash
         working-directory: ./terraform

     steps:

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: ${{ env.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.7.0"

      - name: Run terraform plan
        run: |
           terraform init -backend-config="bucket=${{secrets.AWS_TERRAFORM_BUCKET}}" -backend-config="key=${{secrets.AWS_TERRAFORM_KEY}}" -backend-config="region=${{ env.AWS_REGION }}"
           terraform plan