name: Terraform deployment
on:
  [push, workflow_dispatch]
jobs:
  terraform:
     name: "Terraform working directory"
     runs-on: ubuntu-latest
     defaults:
        run:
         shell: bash
         working-directory: ./terraform

     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.7.0"





